/*
* ==============================================================================
*  Name        : GSProfilesPluginExports.inc
*  Part of     : GSProfilesPlugin
*  Interface   : ?Interface_category, ?Interface_name
*  Description : ?Description
*  Version     : ?Version
*
*  Copyright (c) 2007 Nokia Corporation.
*  This material, including documentation and any related
*  computer programs, is protected by copyright controlled by
*  Nokia Corporation. All rights are reserved. Copying,
*  including reproducing, storing, adapting or translating, any
*  or all of this material requires the prior written consent of
*  Nokia Corporation. This material also contains confidential
*  information which may not be disclosed to others without the
*  prior written consent of Nokia Corporation.
* ==============================================================================
*/
// To get the APP_LAYER_SYSTEMINCLUDE-definition
#include <platform_paths.hrh>

#ifndef GSPROFILESPLUGINEXPORTS_INC
#define GSPROFILESPLUGINEXPORTS_INC

../loc/GSProfilesPlugin.loc    APP_LAYER_LOC_EXPORT_PATH(gsprofilesplugin.loc)

// Export PSM config file
../data/10283386.xml z:/private/2000b187/10283386.xml
#endif      // GSPROFILESPLUGINEXPORTS_INC

// End of File
